# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    cd monitor-service
    chmod +x mvnw
    ./mvnw clean package
  displayName: 'Build monitor service'

- script: |
    cd metrics-service/metrics-service
    chmod +x mvnw
    ./mvnw clean package -DskipTests
  displayName: 'Build metrics service'

- script: |
    echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USERNAME) --password-stdin
  displayName: 'Docker Login'

- script: |
    docker build -t $(DOCKER_USERNAME)/monitor-service:$(Build.BuildId) monitor-service
    docker tag \
    $(DOCKER_USERNAME)/monitor-service:$(Build.BuildId) \
    $(DOCKER_USERNAME)/monitor-service:latest
    docker push $(DOCKER_USERNAME)/monitor-service:$(Build.BuildId)
    docker push $(DOCKER_USERNAME)/monitor-service:latest
  displayName: 'Build & Push Monitor Image'

- script: |
    docker build -t $(DOCKER_USERNAME)/metrics-service:$(Build.BuildId) metrics-service/metrics-service
    docker push $(DOCKER_USERNAME)/metrics-service:$(Build.BuildId)
  displayName: 'Build & Push Metrics Image'



